"""KGW (Kirchenbauer-Geiping-Wen) green-list watermark primitives.

Attribution / upstream source
------------------------------
Ported from:
    transformers.generation.logits_process.WatermarkLogitsProcessor
    (file: generation/logits_process.py, class WatermarkLogitsProcessor,
     "lefthash" seeding scheme only, context_width=1)
Installed version verified: transformers==4.57.6
    (python3 -c "import transformers; print(transformers.__file__)"
     -> .../site-packages/transformers/generation/logits_process.py)
License: Apache-2.0 (huggingface/transformers). See
    https://github.com/huggingface/transformers/blob/main/LICENSE

Only the "lefthash" seeding scheme (context_width=1) is ported here. The
"selfhash" scheme (Algorithm 3 in the KGW paper) is NOT implemented and is
explicitly rejected by KGWConfig.__post_init__ — it needs rejection
sampling over candidate next tokens and is reserved for a later phase.

CRITICAL DEVIATION from transformers (read this before changing anything)
---------------------------------------------------------------------------
transformers' WatermarkLogitsProcessor does:

    self.rng = torch.Generator(device=device)     # device = the model's device
    ...
    self.rng.manual_seed(seed % (2**64 - 1))
    vocab_permutation = torch.randperm(self.vocab_size, device=input_seq.device,
                                        generator=self.rng)

i.e. the permutation is generated by a torch.Generator *seeded on whatever
device generation happens to run on*. torch's Philox/MT RNG streams are NOT
guaranteed identical across devices for the same manual_seed() value (CUDA
uses a different RNG implementation than CPU), so a CUDA-generation run and
a CPU-based detector, seeded identically, are NOT guaranteed to compute the
same greenlist -- generation and detection can silently disagree.

This module ALWAYS builds the permutation with a device-less
(`torch.Generator()`, which defaults to CPU) generator, and returns
CPU LongTensor ids. Callers move the result to whatever device they need
with `.to(device)`. This makes greenlist computation device-independent by
construction: a GPU vLLM generation run and a CPU detector, given the same
key/config, compute the identical greenlist for the identical prev_token.
This is INTENTIONAL and REQUIRED for our use case (GPU-side generation,
CPU-side offline detection) and is a deliberate correctness fix over the
upstream design, not a bug.

Executed check that CPU-generator device is in fact torch's default here:
    torch.Generator().device -> device(type='cpu')   (verified locally,
    torch 2.9.1+cu128, see EXPERIMENTS.md-equivalent test run for Task A)

Seed formula deviation
-----------------------
transformers computes (for lefthash): seed = hash_key * prev_token, then
`self.rng.manual_seed(seed % (2**64 - 1))` -- i.e. it DOES apply a modulus,
but modulo (2**64 - 1), not (2**64). We deliberately use:

    seed = (hash_key * prev_token) % (2**64)

Two things were verified by executing code (not assumed):
  1. torch.Generator().manual_seed(x) accepts any x in [0, 2**64 - 1]
     (raises ValueError("Overflow when unpacking long long") for x == 2**64
     exactly). So both `% (2**64 - 1)` and `% (2**64)` always produce a
     value manual_seed() accepts -- neither modulus is needed to keep
     manual_seed() from raising for in-range values.
  2. For the token-id-scale values transformers is normally invoked with
     (hash_key ~= 10**7-10**8, prev_token < vocab_size <= ~2*10**5), the
     product hash_key * prev_token is always << 2**64 - 1, so BOTH moduli
     are no-ops and (2**64) vs (2**64 - 1) make zero observable difference.
     This is what test_kgw_equivalence.py's greenlist-equivalence test
     exercises, and it is exact-equal, not approximate.
  Our hash_key, however, is derived from sha256(secret)[:8] (see keys.py),
  i.e. a full 64-bit value up to 2**64 - 1. Multiplied by prev_token this
  can genuinely overflow past 2**64, so applying a modulus is NOT optional
  for us the way it is a no-op for transformers' defaults. We use (2**64)
  because it is the natural "wrap a 64-bit hash into unsigned-64-bit
  space" modulus and manual_seed() accepts the full [0, 2**64-1] range
  (see point 1); (2**64 - 1) would be equally safe here but was not what
  was specified for this port, so we do not use it.

KGWConfig.vocab_size is REQUIRED and must be passed explicitly -- it is
NEVER inferred from `len(tokenizer)` or from a logits tensor's last
dimension. Model embedding matrices are frequently padded to a multiple of
8/64/128 for tensor-core efficiency (e.g. Qwen2.5-0.5B-Instruct's
tokenizer vocab and its lm_head output width can differ), and some
tokenizers also grow via `add_tokens` after the model config was fixed. If
generation biases logits[:vocab_size_A] and detection reconstructs
greenlists for logits[:vocab_size_B] with vocab_size_A != vocab_size_B, the
permutation (and therefore the greenlist) is different at every position,
and every z-score silently comes out near zero -- a false "not
watermarked" verdict with no error raised. Callers MUST pass the exact
vocab_size used to build the logits tensor at generation time (i.e. the
model config's vocab_size, not the tokenizer's).
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from numbers import Real

import torch

_SUPPORTED_SEEDING_SCHEMES = ("lefthash",)
_SEED_MODULUS = 1 << 64  # 2**64 -- see "Seed formula deviation" above
_MAX_HASH_KEY = _SEED_MODULUS - 1  # largest value representable in 64 bits
_MAX_VOCAB_SIZE = 1 << 20
_MAX_DELTA = 100.0
# Deployment-safety ceiling for one cached int64 green-list allocation.
_MAX_GREENLIST_BYTES = 4 << 20


@dataclass(frozen=True)
class KGWConfig:
    """Configuration for KGW green-list watermarking (lefthash scheme only).

    Attributes:
        vocab_size: REQUIRED, explicit. See module docstring -- never infer
            this from a tokenizer or from logits.shape[-1]. Must be an
            integer in [1, 2**20].
        hash_key: REQUIRED, explicit. A (secret-derived) 64-bit integer used
            to seed the green-list permutation. Load via keys.py -- never
            hardcode a production value.
        gamma: green-list fraction of the vocabulary, in (0, 1). Equivalent
            to transformers' `greenlist_ratio`. Default 0.25.
        delta: logit bias added to green-list tokens at generation time.
            Equivalent to transformers' `bias`. Default 2.0. (Unused by the
            detector; carried here so one config value drives both sides.)
            Must be finite and in [0, 100].
        seeding_scheme: only "lefthash" is implemented. "selfhash"
            (Algorithm 3 in the KGW paper) is rejected -- reserved for a
            later phase.
        context_width: only 1 is implemented (lefthash conditions on
            exactly the single preceding token).
    """

    vocab_size: int
    hash_key: int
    gamma: float = 0.25
    delta: float = 2.0
    seeding_scheme: str = "lefthash"
    context_width: int = 1
    greenlist_size: int = field(init=False, repr=False)

    def __post_init__(self) -> None:
        if isinstance(self.context_width, bool) or not isinstance(self.context_width, int):
            raise ValueError(
                f"context_width must be an integer, got {self.context_width!r}"
            )
        if self.seeding_scheme not in _SUPPORTED_SEEDING_SCHEMES:
            raise NotImplementedError(
                f"seeding_scheme={self.seeding_scheme!r} is not implemented; "
                f"only {_SUPPORTED_SEEDING_SCHEMES!r} are supported in this port. "
                "selfhash needs rejection sampling over candidate next tokens "
                "(transformers _score_rejection_sampling) and is reserved for "
                "a later phase."
            )
        if self.context_width != 1:
            raise NotImplementedError(
                f"context_width={self.context_width} is not implemented; "
                "only context_width=1 is supported by the lefthash port."
            )

        if isinstance(self.gamma, bool) or not isinstance(self.gamma, Real):
            raise ValueError(f"gamma must be a finite real number, got {self.gamma!r}")
        if not math.isfinite(self.gamma):
            raise ValueError(f"gamma must be finite, got {self.gamma}")
        if not (0.0 < self.gamma < 1.0):
            raise ValueError(f"gamma must be in (0.0, 1.0), got {self.gamma}")

        if isinstance(self.delta, bool) or not isinstance(self.delta, Real):
            raise ValueError(f"delta must be a finite real number, got {self.delta!r}")
        if not math.isfinite(self.delta):
            raise ValueError(f"delta must be finite, got {self.delta}")
        if not (0.0 <= self.delta <= _MAX_DELTA):
            raise ValueError(f"delta must be in [0.0, {_MAX_DELTA}], got {self.delta}")

        if isinstance(self.vocab_size, bool) or not isinstance(self.vocab_size, int):
            raise ValueError(f"vocab_size must be an integer, got {self.vocab_size!r}")
        if not (1 <= self.vocab_size <= _MAX_VOCAB_SIZE):
            raise ValueError(
                f"vocab_size must be in [1, {_MAX_VOCAB_SIZE}], got {self.vocab_size}"
            )

        if isinstance(self.hash_key, bool) or not isinstance(self.hash_key, int):
            raise ValueError(f"hash_key must be an integer, got {self.hash_key!r}")
        if not (0 <= self.hash_key <= _MAX_HASH_KEY):
            raise ValueError(
                f"hash_key must be a non-negative integer < 2**64, got {self.hash_key}"
            )

        greenlist_size = int(self.vocab_size * self.gamma)
        if greenlist_size < 1:
            raise ValueError(
                "effective greenlist_size must be >= 1; increase vocab_size or gamma"
            )
        if greenlist_size * torch.tensor([], dtype=torch.int64).element_size() > _MAX_GREENLIST_BYTES:
            raise ValueError(
                "effective greenlist allocation exceeds the 4 MiB deployment budget; "
                "reduce vocab_size or gamma"
            )
        # frozen dataclass: use object.__setattr__ to set the derived field
        object.__setattr__(self, "greenlist_size", greenlist_size)


def greenlist_ids(prev_token: int, cfg: KGWConfig) -> torch.LongTensor:
    """Compute the green-list token ids seeded by a single preceding token.

    Faithful port of transformers' WatermarkLogitsProcessor.set_seed +
    _get_greenlist_ids for the "lefthash" scheme, EXCEPT: (1) the generator
    is always CPU/device-less (see module docstring "CRITICAL DEVIATION"),
    and (2) the seed modulus is (2**64) instead of transformers'
    (2**64 - 1) (see module docstring "Seed formula deviation").

    Args:
        prev_token: the single preceding token id (int).
        cfg: KGWConfig (seeding_scheme must be "lefthash", context_width=1).

    Returns:
        LongTensor of shape (cfg.greenlist_size,) on CPU, containing the
        green-list token ids for this prev_token under this config. Move to
        another device with `.to(device)` if needed -- this function itself
        never accepts or depends on a device argument.
    """
    seed = (cfg.hash_key * int(prev_token)) % _SEED_MODULUS
    generator = torch.Generator()  # no device arg -> CPU, always
    generator.manual_seed(seed)
    vocab_permutation = torch.randperm(cfg.vocab_size, generator=generator)
    # ``randperm`` owns a vocab-sized storage buffer.  Clone the slice so a
    # cached greenlist retains only its bounded greenlist allocation rather
    # than the entire permutation backing storage.
    return vocab_permutation[: cfg.greenlist_size].clone()
